---
# tasks file for webserver
     - name: Install tomcat app server
       apt: pkg=tomcat8 state=installed update_cache=true

     - name: App distribution
       synchronize: src=/root/repo/target/hello-1.0.war dest=/var/lib/tomcat8/webapps
       delegate_to: 192.168.0.7

       notify:
          - tomcat8 restart

